=== Hodor-Brain/OOPLab2/src/main/java/Xml/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/medicines"
        xmlns:tns="http://www.example.com/medicines"
        elementFormDefault="qualified">
    <element name="Medicines">
        <complexType>
            <sequence>
                <element name="Medicine" type="tns:Medicine" minOccurs="1" maxOccurs="100"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Medicine">
        <sequence>
            <element name="id" type="ID"/>
            <element name="name" type="string"/>
            <element name="pharm" type="tns:Pharm"/>
            <element name="analogs" type="string"/>
            <element name="version" type="tns:Version"/>
        </sequence>
        <attribute name="group" use="optional" default="ANTIBIOTIC">
            <simpleType>
                <restriction base="string">
                    <enumeration value="ANTIBIOTIC"></enumeration>
                    <enumeration value="PAINKILLER"></enumeration>
                    <enumeration value="VITAMIN"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <simpleType name="Pharm">
        <restriction base="NCName">
            <pattern value="([A-Z])[a-zA-Z]{2,10}"/>
        </restriction>
    </simpleType>
    <complexType name="Version">
        <sequence>
            <element name="consistence" type="string"/>
            <element name="certificate" type="tns:Certificate"/>
            <element name="package" type="tns:Package"/>
            <element name="dosage" type="tns:Dosage"/>
        </sequence>
    </complexType>
    <complexType name="Certificate">
        <sequence>
            <element name="number" type="string"/>
            <element name="issuanceDate" type="date"/>
            <element name="expirationDate" type="date"/>
            <element name="organisation" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Package">
        <sequence>
            <element name="type" type="string"/>
            <element name="quantity" type="int"/>
            <element name="price" type="float"/>
        </sequence>
    </complexType>
    <complexType name="Dosage">
        <sequence>
            <element name="dose" type="float"/>
            <element name="regularity" type="int"/>
        </sequence>
    </complexType>
</schema>

=== Hodor-Brain/OOPLab2/src/main/java/Xml/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<Medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/medicines"
         xsi:schemaLocation="http://www.example.com/medicines medicines.xsd">
    <Medicine group="ANTIBIOTIC">
        <id>A1</id>
        <name>Penicillin</name>
        <pharm>Brovafarma</pharm>
        <analogs>none</analogs>
        <version>
            <consistence>Pills</consistence>
            <certificate>
                <number>1A2B</number>
                <issuanceDate>2019-07-21</issuanceDate>
                <expirationDate>2024-07-21</expirationDate>
                <organisation>BigAndHealthy</organisation>
            </certificate>
            <package>
                <type>Plastic</type>
                <quantity>24</quantity>
                <price>109.5</price>
            </package>
            <dosage>
                <dose>0.5</dose>
                <regularity>2</regularity>
            </dosage>
        </version>
    </Medicine>

    <Medicine group="VITAMIN">
        <id>A2</id>
        <name>Magne-B6</name>
        <pharm>VitToHuman</pharm>
        <analogs>Magnemax</analogs>
        <version>
            <consistence>Powder</consistence>
            <certificate>
                <number>7C2D</number>
                <issuanceDate>2020-09-19</issuanceDate>
                <expirationDate>2023-09-19</expirationDate>
                <organisation>BioNTech</organisation>
            </certificate>
            <package>
                <type>Glass</type>
                <quantity>40</quantity>
                <price>246.5</price>
            </package>
            <dosage>
                <dose>1.5</dose>
                <regularity>1</regularity>
            </dosage>
        </version>
    </Medicine>
</Medicines>
